let map,pano,markers=[],monasteries=[],nearbyMarkersMap={},currentMon=null
const lang = localStorage.getItem('lang')||'en'
async function tLoad(){try{const r=await fetch(/translations/${lang}.json); return await r.json()}catch(e){return{}}}
let translations={}
tLoad().then(j=>translations=j)
function t(k,d){return translations[k]||d||k}
async function fetchKey(){const r=await fetch('/api/config/maps-key').catch(()=>null); if(!r) return null; const j=await r.json(); return j.key||null}
async function loadMaps(key){const s=document.createElement('script'); s.src=https://maps.googleapis.com/maps/api/js?key=${key}&libraries=places; s.async=true; s.onload=init; document.head.appendChild(s)}
async function init(){const key = await fetchKey(); if(!key) { alert('Set GOOGLE_MAPS_API_KEY in backend .env'); return } loadMaps(key)}
async function fetchMonasteries(q=''){const r=await fetch('/api/monasteries'+(q??q=${encodeURIComponent(q)}:'')); const j=await r.json(); monasteries=j; renderList(); plotMarkers(); buildSlideshow()}
function renderList(){const el=document.getElementById('list'); el.innerHTML=''; monasteries.forEach((m,i)=>{ const d=document.createElement('div'); d.className='item'; d.dataset.index=i; d.innerHTML=<div><div class='name'>${(m.translations||[]).find(x=>x.lang===lang)?.name||m.name}</div><div>${m.description||''}</div></div>; d.onclick=()=>focusMonastery(i); el.appendChild(d) }) }
function focusMonastery(i){const m=monasteries[i]; currentMon=m; map.panTo({lat:m.latitude,lng:m.longitude}); map.setZoom(14); if(markers[i]) google.maps.event.trigger(markers[i],'click'); showStreetView(m); renderDetails(m); initMiniMap(m)}
function plotMarkers(){markers.forEach(x=>x.setMap(null)); markers=[]; monasteries.forEach((m,i)=>{ const marker=new google.maps.Marker({ map, position:{lat:m.latitude,lng:m.longitude}, title:m.name }); marker.addListener('click', ()=>{ renderDetails(m); showStreetView(m); currentMon=m }); markers.push(marker) }) }
function renderDetails(m){const el=document.getElementById('details'); el.innerHTML=<h2>${(m.translations||[]).find(x=>x.lang===lang)?.name||m.name}</h2><p>${(m.translations||[]).find(x=>x.lang===lang)?.history||m.history||m.description||''}</p><div><button onclick="openTour()" class="btn">${t('open_tour','Open Tour')}</button><button onclick="downloadTour()" class="btn">${t('download_tour','Download Tour')}</button><button onclick="openStory()" class="btn">${t('story_mode','Story Mode')}</button></div> }
function showStreetView(m){const svs=new google.maps.StreetViewService(); const latLng={lat:m.latitude,lng:m.longitude}; svs.getPanorama({location:latLng,radius:500},(data,status)=>{ if(status==='OK'){ const loc=data.location.latLng; pano.setPosition(loc); pano.setPov({heading:m.streetViewHeading||0,pitch:m.streetViewPitch||0}); pano.setVisible(true) } else { pano.setVisible(false) } }) }
function buildSlideshow(){const slidesEl=document.getElementById('slides'); slidesEl.innerHTML = monasteries.map(m=><div class="slide" style="background-image:url('${m.images?.[0]||'/assets/rumtek1.jpg'}')"><div class="meta"><h3>${(m.translations||[]).find(x=>x.lang===lang)?.name||m.name}</h3><div><button onclick="showDetails('${m._id}')">${t('details','Details')}</button></div></div></div>).join(''); let idx=0; document.getElementById('prevSlide').onclick=()=>{ idx=(idx-1+monasteries.length)%monasteries.length; slidesEl.style.transform='translateX('+(-idx*100)+'%)' }; document.getElementById('nextSlide').onclick=()=>{ idx=(idx+1)%monasteries.length; slidesEl.style.transform='translateX('+(-idx*100)+'%)' }; setInterval(()=>{ idx=(idx+1)%monasteries.length; slidesEl.style.transform='translateX('+(-idx*100)+'%)' },5000) }
function showDetails(id){fetch('/api/monasteries/'+id).then(r=>r.json()).then(m=>{ currentMon=m; renderDetails(m); showStreetView(m); initMiniMap(m) }) }
function openTour(){ if(!currentMon) return alert('Select a monastery'); if(window.pannellum && typeof pannellum.viewer === 'function'){ try{ if(window.currentPano) window.currentPano.destroy(); window.currentPano = pannellum.viewer('pannellum-container',{ type:'equirectangular', panorama: currentMon.panoramas?.[0]||currentMon.images?.[0]||'/assets/rumtek1.jpg', autoLoad:true, showControls:true, hotSpots: (currentMon.hotspots||[]).map(h=>({ pitch:h.pitch||0, yaw:h.yaw||0, cssClass:'pn-hotspot', createTooltipFunc:function(hs, el){ el.innerHTML = '<div style="padding:6px;font-size:13px">'+(h.label||h.text||'Info')+'</div>' }, createTooltipArgs:[h.label||h.text||'info'] })) }) }catch(e){ const c=document.getElementById('pannellum-container'); c.innerHTML=<img src="${currentMon.panoramas?.[0]||currentMon.images?.[0]||'/assets/rumtek1.jpg'}" style="width:100%"/> } } else { const c=document.getElementById('pannellum-container'); c.innerHTML=<img src="${currentMon.panoramas?.[0]||currentMon.images?.[0]||'/assets/rumtek1.jpg'}" style="width:100%"/> } }
async function downloadTour(){ if(!currentMon) return alert('Select a monastery'); const urls = (currentMon.panoramas||[]).concat(currentMon.images||[]).concat(currentMon.audio? [currentMon.audio]:[]); if(!urls.length) return alert('No assets'); for(const url of urls){ try{ const r=await fetch(url); const b=await r.blob(); await idbPut('assets',{ key:'asset:'+url, url, blob:b }); const cache = await caches.open('echoes-cache-v4'); try{ await cache.add(url) }catch(e){} }catch(e){} } alert('Saved for offline') }
function openStory(){ if(!currentMon) return alert('Select a monastery'); const modal=document.getElementById('storyModal'); const content=document.getElementById('storyContent'); content.innerHTML = <h2>${(currentMon.translations||[]).find(x=>x.lang===lang)?.name||currentMon.name}</h2><div>${(currentMon.translations||[]).find(x=>x.lang===lang)?.history||currentMon.history||currentMon.description||''}</div>; modal.style.display='block'; const audioUrl=currentMon.audio||null; if(audioUrl){ if(window.storyAudio) window.storyAudio.pause(); window.storyAudio=new Audio(audioUrl) } document.getElementById('playStory').onclick=()=>{ if(window.storyAudio) window.storyAudio.play() }; document.getElementById('pauseStory').onclick=()=>{ if(window.storyAudio) window.storyAudio.pause() }; document.getElementById('downloadStory').onclick=async ()=>{ if(!audioUrl) return alert('No audio'); await downloadAudioToIdb(audioUrl); alert('Saved for offline') }; document.getElementById('closeStory').onclick=()=>{ modal.style.display='none'; if(window.storyAudio) window.storyAudio.pause() } }
async function downloadAudioToIdb(url){ try{ const r=await fetch(url); const b=await r.blob(); await idbPut('assets',{ key:'asset:'+url, url, blob:b }); return true }catch(e){ return false } }
function openIdb(){ return new Promise((res,rej)=>{ const req=indexedDB.open('echoes-db',2); req.onupgradeneeded=e=>{ const db=e.target.result; if(!db.objectStoreNames.contains('assets')) db.createObjectStore('assets',{ keyPath:'key' }); if(!db.objectStoreNames.contains('routes')) db.createObjectStore('routes',{ keyPath:'id' }) }; req.onsuccess=()=>res(req.result); req.onerror=()=>rej(req.error) }) }
async function idbPut(store,obj){ const db=await openIdb(); return new Promise((res,rej)=>{ const tx=db.transaction(store,'readwrite'); const s=tx.objectStore(store); s.put(obj); tx.oncomplete=()=>res(true); tx.onerror=()=>rej(tx.error) }) }
async function idbGet(store,key){ const db=await openIdb(); return new Promise((res,rej)=>{ const tx=db.transaction(store,'readonly'); const s=tx.objectStore(store); const r=s.get(key); r.onsuccess=()=>res(r.result); r.onerror=()=>rej(r.error) }) }
async function downloadRouteForMonastery(m){ if(!navigator.geolocation) return alert('GPS not available'); navigator.geolocation.getCurrentPosition(async pos=>{ const lat=pos.coords.latitude, lng=pos.coords.longitude; try{ const r=await fetch(/api/routes/${m._id}?lat=${lat}&lng=${lng}); const j=await r.json(); if(j.steps){ await idbPut('routes',{ id:route:${m._id}:${lat.toFixed(3)},${lng.toFixed(3)}, monastery:m._id, origin:{lat,lng}, steps:j.steps }); alert('Route saved for offline') } else alert('No route') }catch(e){ alert('Failed') } }, err=>alert('GPS failed:'+err.message)) }
async function startOfflineNavigation(m){ if(!navigator.geolocation) return alert('GPS not available'); navigator.geolocation.getCurrentPosition(async pos=>{ const lat=pos.coords.latitude, lng=pos.coords.longitude; const db=await openIdb(); const tx=db.transaction('routes','readonly'); const store=tx.objectStore('routes'); const all=await store.getAll(); let best=null, bestD=1e9; for(const rt of all){ if(rt.monastery!==m._id) continue; const d=Math.hypot(rt.origin.lat-lat, rt.origin.lng-lng); if(d<bestD){ best=rt; bestD=d } } if(!best) return alert('No offline route cached'); const steps=best.steps; let idx=0; const navMarker=new google.maps.Marker({ map, position:{lat:lat,lng:lng}, icon:{path:google.maps.SymbolPath.CIRCLE,scale:6,fillColor:'#ff0000',fillOpacity:1,strokeColor:'#fff'} }); function speak(text){ const u=new SpeechSynthesisUtterance(text); u.lang = localStorage.getItem('lang')||'en-US'; speechSynthesis.speak(u) } function next(){ if(idx>=steps.length){ speak('Arrived'); return } const step=steps[idx]; const instr=step.html_instructions.replace(/<[^>]+>/g,''); speak(instr); const path=[step.start_location, step.end_location].map(s=>({lat:s.lat,lng:s.lng})); const poly=new google.maps.Polyline({ path, strokeColor:'#2563eb', strokeOpacity:0.9, strokeWeight:4, map }); navMarker.setPosition({lat:step.end_location.lat,lng:step.end_location.lng}); idx++; setTimeout(next,7000) } next() }, err=>alert('GPS failed:'+err.message)) }
async function syncRoutes(){ try{ const r=await fetch('/api/routes'); const list=await r.json(); for(const rt of list){ await idbPut('routes',{ id:route:${rt.monastery._id}:${rt.origin?.lat?.toFixed?.(3)||0},${rt.origin?.lng?.toFixed?.(3)||0}, monastery:rt.monastery._id, origin:rt.origin, steps:rt.steps }) } }catch(e){} }
function initMiniMap(monastery){ const wrap=document.getElementById('minimap-wrap'); const toggle=document.getElementById('minimap-toggle'); const saved=JSON.parse(localStorage.getItem('miniMapState')||'{}'); if(saved.top) wrap.style.top=saved.top; if(saved.left) wrap.style.left=saved.left; if(saved.width) wrap.style.width=saved.width; if(saved.height) wrap.style.height=saved.height; if(localStorage.getItem('miniMap')===null){ const ask=confirm("Enable Mini-Map?"); localStorage.setItem('miniMap', ask?'true':'false') } function load(){ wrap.style.display='block'; const mini=new google.maps.Map(document.getElementById('minimap'),{ center:{ lat:monastery.latitude, lng:monastery.longitude }, zoom:13, disableDefaultUI:true }); new google.maps.Marker({ position:{ lat:monastery.latitude, lng:monastery.longitude }, map:mini }); if(navigator.geolocation){ navigator.geolocation.getCurrentPosition(pos=>{ new google.maps.Marker({ position:{ lat:pos.coords.latitude, lng:pos.coords.longitude }, map:mini, icon:{ path:google.maps.SymbolPath.CIRCLE, scale:6, fillColor:'#f00', fillOpacity:1, strokeColor:'#fff' } }) }) } } if(localStorage.getItem('miniMap')==='true') load(); else wrap.style.display='none'; toggle.onclick=()=>{ if(localStorage.getItem('miniMap')==='true'){ localStorage.setItem('miniMap','false'); wrap.style.display='none' } else { localStorage.setItem('miniMap','true'); load() } }; let dragging=false, startX, startY, sTop, sLeft; wrap.addEventListener('mousedown', e=>{ if(e.target!==wrap) return; dragging=true; startX=e.clientX; startY=e.clientY; sTop=wrap.offsetTop; sLeft=wrap.offsetLeft; e.preventDefault() }); window.addEventListener('mousemove', e=>{ if(!dragging) return; const dx=e.clientX-startX, dy=e.clientY-startY; wrap.style.top = sTop+dy+'px'; wrap.style.left = sLeft+dx+'px' }); window.addEventListener('mouseup', ()=>{ if(dragging){ dragging=false; save() } }); new ResizeObserver(()=>save()).observe(wrap); function save(){ localStorage.setItem('miniMapState', JSON.stringify({ top: wrap.style.top, left: wrap.style.left, width: wrap.style.width, height: wrap.style.height })) } }
document.getElementById('topSearchBtn').onclick=()=>fetchMonasteries(document.getElementById('topSearch').value)
document.getElementById('chatOpen').onclick=()=>{ const modal=document.createElement('div'); modal.style='position:fixed;left:50%;top:10%;transform:translateX(-50%);background:#fff;padding:12px;border-radius:10px;z-index:400;max-width:720px;max-height:70%;overflow:auto'; modal.innerHTML=<div style="display:flex;gap:8px"><input id="chatQ" style="flex:1;padding:8px"><button id="sendChat">Send</button><button id="closeChat">Close</button></div><div id="chatOut" style="margin-top:10px"></div>; document.body.appendChild(modal); modal.querySelector('#closeChat').onclick=()=>modal.remove(); modal.querySelector('#sendChat').onclick=async ()=>{ const q=modal.querySelector('#chatQ').value; if(!q) return; const out=modal.querySelector('#chatOut'); out.innerHTML+=<div><strong>You</strong>: ${q}</div>; const r=await fetch('/api/chatbot',{ method:'POST', headers:{'Content-Type':'application/json'}, body:JSON.stringify({ q }) }); const j=await r.json(); out.innerHTML+=<div><strong>Assistant</strong>: <pre style="white-space:pre-wrap">${j.answer||j.error||JSON.stringify(j)}</pre></div> } }
window.addEventListener('load', ()=>{ fetchMonasteries(); syncRoutes() })
